### ISSUE TITLE
Привести структуру проекта в порядок

### ISSUE THREAD

**Issue by AnnaQC** [Alexsolo1996/GeoApteka-2#1]
1.По организации:
Почему не следуешь правилам оформления кода на Джаве? 
Ознакомься с  https://yar.fruct.org/projects/common-info/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BA_%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8_%D0%B8_%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E_%D0%BA%D0%BE%D0%B4%D0%B0_(Java) и http://www.oracle.com/technetwork/java/codeconventions-150003.pdf  и приведи в порядок весь проект.
Элементарный пример. Ты именуешь пакеты с большой буквы, принято использовать только строчные сиволы в именах пакетов.("Привести в порядок" не означает что тебе надо поправить только имена пакетов) 
2. Давай соответсвующие, осмысленные и читабельные названия пакетам, классам, методам и папкам.
Примеры. название калсса тестового набора должно кратко отображать цель твоих тестов (название тест сьюта, обычно именуется как функциональность которую ты тестируешь). **Например SortTestForStartPage.** Если уже ты привязываешься к начальному состоянию страницы то до момента поиска препарата функционал аптек не доступен.  В этом сьюте ты ведь не тесты сортируешь на стартовой странице(судя по названию, а список аптек), поэтому логичнее назвать SortDrugStoresTest или более обобощенно AptekaTabTests(по названию тестового сьюта в доке, которую я тебе предоставила , он же - тестируемой функциональность, на случай если мы будем добавлять новые проверки по работе с вкладкой аптек.) 
SuppMethod - содержит методы выбора элементов, searchElem, searchElem1 и пр. Никогда не именуй так ключевые методы, которые ты используешь, ты не сможешь поддерживать большой проект, название метода должно отображать конечный результат, мы же не в бирюльки играем, каждая такая шалость выливается в часы при поддержке тестов, при чем не только твои или уже тогда джавадок делай по каждому такому методу + коммент.  
3. Приведи в порядок pom. Убери лишние зависимости, если используешь testNG то убери зависимости по JUNIT и наоборот
4. Логи складывай в папку logs в корне проекта

По логике и архитектуре
1. Убери локаторы из класса BaseTest, там не должно быть ничего кроме инициализации драйвера и жизненноважных параметров тестов (например Базовый адресс рессурса), а также обработки параметров завершения тестов(например закрытие драйвера в нашем случае). Наследоваться от него должны только тестовые классы.
2. Не наследуй SuppMethod от BaseTest. лучше сделай его базовым (это ведь оббертка над вебдрайвером) и уже его будут наследовать классы в которых ты работаешь с этими методами, например классы страниц.
3. Добавляй информативные сообщения в каждый ассерт. Ассерт - это то ради, чего мы и работаем, первое, на что обращается внимание это ассерт а не лог.
4. По самой логике тестовых методов будем розбираться отдельно

**Comment by Alexsolo1996** [comment]
Ок

31 мар 2017 г. 5:59 PM пользователь "annaQC" <notifications@github.com>
написал:

**Comment by Alexsolo1996** [comment]
Close
